setenv AMPTOOLS_VERSION 0.6.2
setenv CLHEP_INCLUDE_DIR $CLHEP_INCLUDE
setenv CLHEP_LIB_DIR $CLHEP_LIB
setenv AMPTOOLS_HOME $GLUEX_TOP/AmpTools/AmpTools_v$AMPTOOLS_VERSION
setenv AMPTOOLS $AMPTOOLS_HOME/AmpTools
setenv AMPPLOTTER $AMPTOOLS_HOME/AmpPlotter
 
