#!/bin/bash
echo HALLD_HOME = $HALLD_HOME
echo HDDS_HOME = $HDDS_HOME
echo JANA_HOME = $JANA_HOME
echo CCDB_HOME = $CCDB_HOME
echo ROOTSYS = $ROOTSYS
echo CERN_ROOT = $CERN_ROOT
echo XERCESCROOT = $XERCESCROOT
