@packages = (root, clhep, jana, 'sim-recon', hdds, cernlib,
	     'xerces-c', ccdb, geant4, evio, rcdb, hdgeant4,
	     hd_utilities, gluex_root_analysis, amptools, sqlitecpp, sqlite,
	     gluex_MCwrapper, halld_sim, halld_recon, lapack, hepmc, photos,
	     evtgen, diracxx, hddm, halld_amp);

%home_variable = (root => 'ROOTSYS',
		  clhep => 'CLHEP',
		  jana => 'JANA_HOME',
		  'sim-recon' => 'HALLD_HOME',
		  hdds => 'HDDS_HOME',
		  cernlib => 'CERN',
		  'xerces-c' => 'XERCESCROOT',
		  geant4 => 'G4ROOT',
		  ccdb => 'CCDB_HOME',
		  evio => 'EVIOROOT',
		  rcdb => 'RCDB_HOME',
                  hdgeant4 => 'HDGEANT4_HOME',
                  hd_utilities => 'HD_UTILITIES_HOME',
                  gluex_root_analysis => 'ROOT_ANALYSIS_HOME',
                  amptools => 'AMPTOOLS_HOME',
                  sqlitecpp => 'SQLITECPP_HOME',
		  sqlite => 'SQLITE_HOME',
		  gluex_MCwrapper => 'MCWRAPPER_CENTRAL',
                  halld_sim => 'HALLD_SIM_HOME',
                  halld_recon => 'HALLD_RECON_HOME',
		  lapack => 'LAPACK_HOME',
		  hepmc => 'HEPMCDIR',
		  photos => 'PHOTOSDIR',
		  evtgen => 'EVTGENDIR',
		  diracxx => 'DIRACXX_HOME',
		  hddm => 'HDDM_HOME',
		  halld_amp => 'HALLD_AMP_HOME');

%dir_prefix = (root => 'root[_-]',
	       clhep => '',
	       jana => 'jana_',
	       'sim-recon' => 'sim-recon-',
	       hdds => 'hdds-',
	       cernlib => 'special case',
	       'xerces-c' => 'xerces-c-',
	       geant4 => 'geant4.',
	       ccdb => 'ccdb_',
	       evio => 'evio-',
	       rcdb => 'rcdb_',
               hdgeant4 => 'hdgeant4-',
               hd_utilities => 'hd_utilities-',
               gluex_root_analysis => 'gluex_root_analysis-',
               amptools => 'AmpTools-',
               sqlitecpp => 'SQLiteCpp-',
               sqlite => 'sqlite-',
               gluex_MCwrapper => 'gluex_MCwrapper-',
               halld_sim => 'halld_sim-',
               halld_recon => 'halld_recon-',
	       lapack => 'lapack-',
	       hepmc => 'HepMC-',
	       photos => 'Photos-',
	       evtgen => 'evtgen-',
	       diracxx => 'Diracxx-',
	       hddm => 'hddm-',
	       halld_amp => 'halld_amp-');

$unames = `uname -s`;
chomp $unames;
$unamem = `uname -m`;
chomp $unamem;
$evio_suffix = '/' . $unames . '-' . $unamem;
%dir_suffix = (root => '',
	       clhep => '',
	       jana => '/' . $bms_osname,
	       'sim-recon' => '',
	       hdds => '',
	       cernlib => '',
	       'xerces-c' => '',
	       geant4 => '',
	       ccdb => '',
	       evio => $evio_suffix,
	       rcdb => '',
               hdgeant4 => '',
               hd_utilities => '',
               gluex_root_analysis => '',
               amptools => '',
               sqlitecpp => '',
               sqlite => '',
               gluex_MCwrapper => '',
               halld_sim => '',
               halld_recon => '',
               lapack => '',
               hepmc => '',
               photos => '',
               evtgen => '',
	       diracxx => '',
	       hddm => '',
	       halld_amp => '');
@debug_type = ('', 'optdbg', 'dbg');
